version: "3"
services:
    bts-database:
        image: postgres:10.1
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
          - POSTGRES_HOST=database
        volumes:
            - ./db/setup:/docker-entrypoint-initdb.d
        ports:
            - "5432:5432"
        network_mode: "bridge"
        container_name: "bts-ce-database"
        command: ["postgres","-c","max_locks_per_transaction=1024"]
    bts-msgbroker:
        image: rabbitmq:3.7.4-management
        restart: always
        ports:
            - "4369:4369"
            - "5671:5671"
            - "5672:5672"
            - "15672:15672"
            - "15674:15674"
            - "61613:61613"
            - "15670:15670"
        network_mode: "bridge"
        container_name: "bts-ce-msgbroker"
        command: bash -c "rabbitmq-server; rabbitmq-plugins enable rabbitmq_web_stomp"
    bts-api:
        image: registry.gitlab.com/bts-ce/bts-ce-api
        ports:
          - 8181:8181
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
          - BTS_DB_HOST=database
          - BTS_DB_NAME=bts
          - BTS_DB_USER=bodastage
          - BTS_DB_PASS=password
          - BTS_DB_PORT=5432
        volumes:
          - ./bts-ce-api:/app
          - ./bts-ce-database:/migrations
        depends_on:
            - bts-database
            - bts-msgbroker
        links:
          - "bts-database:database"
        network_mode: "bridge"
        container_name: "bts-ce-api"
        command: ["/wait-for-it.sh","database:5432","--","/migrate-and-start-web-server.sh"]
    bts-web:
        image: registry.gitlab.com/bts-ce/bts-ce-web
        ports:
          - "80:80"
        network_mode: "bridge"
        container_name: "bts-ce-web"
        depends_on:
            - bts-msgbroker
            - bts-api
    bts-mediation:
        image: registry.gitlab.com/bts-ce/bts-ce-mediation
        restart: always
        environment:
          - POSTGRES_PASSWORD=password
        ports:
          - "8080:8080"
        environment:
            - POSTGRES_HOST=database
            - AIRFLOW__CORE__SQL_ALCHEMY_CONN=postgres+psycopg2://airflow:airflow@database:5432/airflow
            - AIRFLOW__CORE__EXECUTOR=LocalExecutor
            - LOAD_EX=n
            - EXECUTOR=Local
            - BTS_DB_HOST=database
            - BTS_DB_NAME=bts
            - BTS_DB_USER=bodastage
            - BTS_DB_PASS=password
            - BTS_DB_PORT=5432
        volumes:
           - ./mediation/dags:/usr/local/airflow/dags
           - ./mediation:/mediation
        command: webserver
        depends_on:
           - bts-database
           - bts-msgbroker
        network_mode: "bridge"
        container_name: "bts-ce-mediation"
        links:
            - "bts-database:database"
    bts-cache:
        image: redis:latest
        ports:
          - "6380:6380"
        network_mode: "bridge"
        container_name: "bts-ce-cache"
    bts-ftp:
        image: stilliard/pure-ftpd:hardened
        restart: always
        environment:
          - PUBLICHOST=localhost
          - ADDED_FLAGS=-d -d
          - FTP_USER_NAME=bodastage
          - FTP_USER_PASS=Password@7
          - FTP_USER_HOME=/home/ftpusers/bodastage
        ports:
          - "21:21"
          - "30000-30009:30000-30009"
        volumes:
           - /home/bodastage/bts-ce/mediation/data:/home/ftpusers/bodastage
        network_mode: "bridge"
        container_name: "bts-ce-ftp"
    #    command: ["pure-pw","useradd","bodastage","-f", "/etc/pure-ftpd/passwd/pureftpd.passwd", "-m", "-u", "ftpuser", "-d", "/home/ftpusers/bodastage"]